In [1]:
import pandas as pd
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [2]:
data.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
from sklearn.model_selection import train_test_split
train, test=train_test_split(data)

In [4]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1319,9.1,0.76,0.68,1.7,0.414,18.0,64.0,0.99652,2.90,1.33,9.1,6
1585,7.2,0.39,0.44,2.6,0.066,22.0,48.0,0.99494,3.30,0.84,11.5,6
888,6.8,0.57,0.00,2.5,0.072,32.0,64.0,0.99491,3.43,0.56,11.2,6
227,9.0,0.82,0.14,2.6,0.089,9.0,23.0,0.99840,3.39,0.63,9.8,5
879,7.2,0.60,0.04,2.5,0.076,18.0,88.0,0.99745,3.53,0.55,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1095,9.4,0.40,0.47,2.5,0.087,6.0,20.0,0.99772,3.15,0.50,10.5,5
1301,6.7,0.86,0.07,2.0,0.100,20.0,57.0,0.99598,3.60,0.74,11.7,6
382,8.3,0.26,0.42,2.0,0.080,11.0,27.0,0.99740,3.21,0.80,9.4,6
619,11.3,0.37,0.41,2.3,0.088,6.0,16.0,0.99880,3.09,0.80,9.3,5
168,6.8,0.63,0.07,2.1,0.089,11.0,44.0,0.99530,3.47,0.55,10.4,6